export const brazilianStatesOptions = [
    {value: "ACRE", label: "Acre"},
    {value: "ALAGOAS", label: "Alagoas"},
    {value: "AMAPA", label: "Amapá"},
    {value: "AMAZONAS", label: "Amazonas"},
    {value: "BAHIA", label: "Bahia"},
    {value: "CEARA", label: "Ceará"},
    {value: "DISTRITO-FEDERAL", label: "Distrito Federal"},
    {value: "ESPIRITO-SANTO", label: "Espírito Santo"},
    {value: "GOIAS", label: "Goiás"},
    {value: "MARANHAO", label: "Maranhão"},
    {value: "MATO-GROSSO", label: "Mato Grosso"},
    {value: "MATO-GROSSO-SUL", label: "Mato Grosso do Sul"},
    {value: "MINAS-GERAIS", label: "Minas Gerais"},
    {value: "PARA", label: "Pará"},
    {value: "PARAIBA", label: "Paraíba"},
    {value: "PARANA", label: "Paraná"},
    {value: "PERNAMBUCO", label: "Pernambuco"},
    {value: "PIAUI", label: "Piauí"},
    {value: "RIO-DE-JANEIRO", label: "Rio de Janeiro"},
    {value: "RIO-GRANDE-NORTE", label: "Rio Grande do Norte"},
    {value: "RIO-GRANDE-SUL", label: "Rio Grande do Sul"},
    {value: "RONDONIA", label: "Rondônia"},
    {value: "RORAIMA", label: "Roraima"},
    {value: "SANTA-CATARINA", label: "Santa Catarina"},
    {value: "SAO-PAULO", label: "São Paulo"},
    {value: "SERGIPE", label: "Sergipe"},
    {value: "TOCANTINS", label: "Tocantins"},
]